language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
node_js:
  - "10.15.1"
install:
  - yarn install
jobs:
  include:
    - stage: 'Tests'
      name: 'Unit Tests'
      script: yarn test
